[package]
name = "muninn"
version = "0.5.0"
edition = "2021"

[lib]
name = "muninn"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37.0"
tantivy = { git = "https://github.com/quickwit-oss/tantivy", rev = "b11605f045d3f8faf9324a7cc7a20bac41199948" }
regex = "1.11"

[features]
default = ["nif_version_2_15"]
nif_version_2_15 = ["rustler/nif_version_2_15"]
nif_version_2_16 = ["rustler/nif_version_2_16"]

[profile.release]
lto = true
opt-level = 3
